FROM openjdk:11-jdk-slim as build
WORKDIR /workspace

COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY common common
COPY inventory inventory

RUN ./gradlew -Dorg.gradle.daemon=false :inventory:assemble
RUN mkdir -p inventory/build/libs/dependency && (cd inventory/build/libs/dependency; jar -xf ../*.jar)

FROM openjdk:11-jdk-slim
VOLUME /tmp
VOLUME /log
EXPOSE 8080
ARG DEPENDENCY=/workspace/inventory/build/libs/dependency
COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build ${DEPENDENCY}/BOOT-INF/classes /app
ENTRYPOINT ["java","-cp","app:app/lib/*","li.doerf.microstore.inventory.InventoryApplicationKt"]
