FROM openjdk:11-jdk-slim as build
WORKDIR /workspace

COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY common common
COPY customer customer

RUN ./gradlew -Dorg.gradle.daemon=false :customer:assemble
RUN mkdir -p customer/build/libs/dependency && (cd customer/build/libs/dependency; jar -xf ../*.jar)

FROM openjdk:11-jdk-slim
VOLUME /tmp
VOLUME /log
EXPOSE 8080
ARG DEPENDENCY=/workspace/customer/build/libs/dependency
COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build ${DEPENDENCY}/BOOT-INF/classes /app
ENTRYPOINT ["java","-cp","app:app/lib/*","li.doerf.cloudstore.customer.CustomerApplicationKt"]

